// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/openshift-online/openshellctl/pkg/gateway (interfaces: Gateway)
//
// Generated by this command:
//
//	mockgen -destination=mock/gateway_mock.go -package=mock . Gateway
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	v1 "github.com/NVIDIA/OpenShell/sdk/go/openshell/v1"
	types "github.com/NVIDIA/OpenShell/sdk/go/openshell/v1/types"
	openshellv1 "github.com/NVIDIA/OpenShell/sdk/go/proto/openshellv1"
	gateway "github.com/openshift-online/openshellctl/pkg/gateway"
	gomock "go.uber.org/mock/gomock"
)

// MockGateway is a mock of Gateway interface.
type MockGateway struct {
	ctrl     *gomock.Controller
	recorder *MockGatewayMockRecorder
	isgomock struct{}
}

// MockGatewayMockRecorder is the mock recorder for MockGateway.
type MockGatewayMockRecorder struct {
	mock *MockGateway
}

// NewMockGateway creates a new mock instance.
func NewMockGateway(ctrl *gomock.Controller) *MockGateway {
	mock := &MockGateway{ctrl: ctrl}
	mock.recorder = &MockGatewayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateway) EXPECT() *MockGatewayMockRecorder {
	return m.recorder
}

// AttachProvider mocks base method.
func (m *MockGateway) AttachProvider(ctx context.Context, workspace, sandbox, provider string, expectedRV uint64) (*types.Sandbox, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AttachProvider", ctx, workspace, sandbox, provider, expectedRV)
	ret0, _ := ret[0].(*types.Sandbox)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AttachProvider indicates an expected call of AttachProvider.
func (mr *MockGatewayMockRecorder) AttachProvider(ctx, workspace, sandbox, provider, expectedRV any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AttachProvider", reflect.TypeOf((*MockGateway)(nil).AttachProvider), ctx, workspace, sandbox, provider, expectedRV)
}

// CreateSandbox mocks base method.
func (m *MockGateway) CreateSandbox(ctx context.Context, workspace, name string, spec *types.SandboxSpec, labels map[string]string) (*types.Sandbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSandbox", ctx, workspace, name, spec, labels)
	ret0, _ := ret[0].(*types.Sandbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSandbox indicates an expected call of CreateSandbox.
func (mr *MockGatewayMockRecorder) CreateSandbox(ctx, workspace, name, spec, labels any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSandbox", reflect.TypeOf((*MockGateway)(nil).CreateSandbox), ctx, workspace, name, spec, labels)
}

// CurrentUser mocks base method.
func (m *MockGateway) CurrentUser(ctx context.Context) (*types.CurrentUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CurrentUser", ctx)
	ret0, _ := ret[0].(*types.CurrentUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CurrentUser indicates an expected call of CurrentUser.
func (mr *MockGatewayMockRecorder) CurrentUser(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CurrentUser", reflect.TypeOf((*MockGateway)(nil).CurrentUser), ctx)
}

// DeleteSandbox mocks base method.
func (m *MockGateway) DeleteSandbox(ctx context.Context, workspace, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSandbox", ctx, workspace, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSandbox indicates an expected call of DeleteSandbox.
func (mr *MockGatewayMockRecorder) DeleteSandbox(ctx, workspace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSandbox", reflect.TypeOf((*MockGateway)(nil).DeleteSandbox), ctx, workspace, name)
}

// DetachProvider mocks base method.
func (m *MockGateway) DetachProvider(ctx context.Context, workspace, sandbox, provider string, expectedRV uint64) (*types.Sandbox, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetachProvider", ctx, workspace, sandbox, provider, expectedRV)
	ret0, _ := ret[0].(*types.Sandbox)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DetachProvider indicates an expected call of DetachProvider.
func (mr *MockGatewayMockRecorder) DetachProvider(ctx, workspace, sandbox, provider, expectedRV any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetachProvider", reflect.TypeOf((*MockGateway)(nil).DetachProvider), ctx, workspace, sandbox, provider, expectedRV)
}

// ExecSandbox mocks base method.
func (m *MockGateway) ExecSandbox(ctx context.Context, req *openshellv1.ExecSandboxRequest) (gateway.Stream[*openshellv1.ExecSandboxEvent], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecSandbox", ctx, req)
	ret0, _ := ret[0].(gateway.Stream[*openshellv1.ExecSandboxEvent])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecSandbox indicates an expected call of ExecSandbox.
func (mr *MockGatewayMockRecorder) ExecSandbox(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecSandbox", reflect.TypeOf((*MockGateway)(nil).ExecSandbox), ctx, req)
}

// ExecSandboxInteractive mocks base method.
func (m *MockGateway) ExecSandboxInteractive(ctx context.Context) (gateway.BidiStream, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecSandboxInteractive", ctx)
	ret0, _ := ret[0].(gateway.BidiStream)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecSandboxInteractive indicates an expected call of ExecSandboxInteractive.
func (mr *MockGatewayMockRecorder) ExecSandboxInteractive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecSandboxInteractive", reflect.TypeOf((*MockGateway)(nil).ExecSandboxInteractive), ctx)
}

// GetGatewayConfig mocks base method.
func (m *MockGateway) GetGatewayConfig(ctx context.Context) (*types.GatewayConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGatewayConfig", ctx)
	ret0, _ := ret[0].(*types.GatewayConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGatewayConfig indicates an expected call of GetGatewayConfig.
func (mr *MockGatewayMockRecorder) GetGatewayConfig(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGatewayConfig", reflect.TypeOf((*MockGateway)(nil).GetGatewayConfig), ctx)
}

// GetLogs mocks base method.
func (m *MockGateway) GetLogs(ctx context.Context, workspace, sandbox string, opts ...types.LogOption) (*types.LogResult, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, workspace, sandbox}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLogs", varargs...)
	ret0, _ := ret[0].(*types.LogResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLogs indicates an expected call of GetLogs.
func (mr *MockGatewayMockRecorder) GetLogs(ctx, workspace, sandbox any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, workspace, sandbox}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLogs", reflect.TypeOf((*MockGateway)(nil).GetLogs), varargs...)
}

// GetSandbox mocks base method.
func (m *MockGateway) GetSandbox(ctx context.Context, workspace, name string) (*types.Sandbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSandbox", ctx, workspace, name)
	ret0, _ := ret[0].(*types.Sandbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSandbox indicates an expected call of GetSandbox.
func (mr *MockGatewayMockRecorder) GetSandbox(ctx, workspace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSandbox", reflect.TypeOf((*MockGateway)(nil).GetSandbox), ctx, workspace, name)
}

// GetSandboxConfig mocks base method.
func (m *MockGateway) GetSandboxConfig(ctx context.Context, workspace, sandbox string) (*types.SandboxConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSandboxConfig", ctx, workspace, sandbox)
	ret0, _ := ret[0].(*types.SandboxConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSandboxConfig indicates an expected call of GetSandboxConfig.
func (mr *MockGatewayMockRecorder) GetSandboxConfig(ctx, workspace, sandbox any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSandboxConfig", reflect.TypeOf((*MockGateway)(nil).GetSandboxConfig), ctx, workspace, sandbox)
}

// ListProviders mocks base method.
func (m *MockGateway) ListProviders(ctx context.Context, workspace string, opts types.ListOptions) ([]*types.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProviders", ctx, workspace, opts)
	ret0, _ := ret[0].([]*types.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProviders indicates an expected call of ListProviders.
func (mr *MockGatewayMockRecorder) ListProviders(ctx, workspace, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProviders", reflect.TypeOf((*MockGateway)(nil).ListProviders), ctx, workspace, opts)
}

// ListSandboxProviders mocks base method.
func (m *MockGateway) ListSandboxProviders(ctx context.Context, workspace, sandbox string) ([]*types.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSandboxProviders", ctx, workspace, sandbox)
	ret0, _ := ret[0].([]*types.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSandboxProviders indicates an expected call of ListSandboxProviders.
func (mr *MockGatewayMockRecorder) ListSandboxProviders(ctx, workspace, sandbox any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSandboxProviders", reflect.TypeOf((*MockGateway)(nil).ListSandboxProviders), ctx, workspace, sandbox)
}

// ListSandboxes mocks base method.
func (m *MockGateway) ListSandboxes(ctx context.Context, workspace string, opts types.ListOptions) ([]*types.Sandbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSandboxes", ctx, workspace, opts)
	ret0, _ := ret[0].([]*types.Sandbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSandboxes indicates an expected call of ListSandboxes.
func (mr *MockGatewayMockRecorder) ListSandboxes(ctx, workspace, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSandboxes", reflect.TypeOf((*MockGateway)(nil).ListSandboxes), ctx, workspace, opts)
}

// SSHTunnel mocks base method.
func (m *MockGateway) SSHTunnel(ctx context.Context, workspace, sandbox string) (io.ReadWriteCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SSHTunnel", ctx, workspace, sandbox)
	ret0, _ := ret[0].(io.ReadWriteCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SSHTunnel indicates an expected call of SSHTunnel.
func (mr *MockGatewayMockRecorder) SSHTunnel(ctx, workspace, sandbox any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SSHTunnel", reflect.TypeOf((*MockGateway)(nil).SSHTunnel), ctx, workspace, sandbox)
}

// StartSandbox mocks base method.
func (m *MockGateway) StartSandbox(ctx context.Context, workspace, name string) (*types.Sandbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartSandbox", ctx, workspace, name)
	ret0, _ := ret[0].(*types.Sandbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StartSandbox indicates an expected call of StartSandbox.
func (mr *MockGatewayMockRecorder) StartSandbox(ctx, workspace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartSandbox", reflect.TypeOf((*MockGateway)(nil).StartSandbox), ctx, workspace, name)
}

// StopSandbox mocks base method.
func (m *MockGateway) StopSandbox(ctx context.Context, workspace, name string) (*types.Sandbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StopSandbox", ctx, workspace, name)
	ret0, _ := ret[0].(*types.Sandbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StopSandbox indicates an expected call of StopSandbox.
func (mr *MockGatewayMockRecorder) StopSandbox(ctx, workspace, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StopSandbox", reflect.TypeOf((*MockGateway)(nil).StopSandbox), ctx, workspace, name)
}

// TCPListen mocks base method.
func (m *MockGateway) TCPListen(ctx context.Context, workspace, sandbox string, remotePort, localPort uint32, bind string) (v1.ForwardListener, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TCPListen", ctx, workspace, sandbox, remotePort, localPort, bind)
	ret0, _ := ret[0].(v1.ForwardListener)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TCPListen indicates an expected call of TCPListen.
func (mr *MockGatewayMockRecorder) TCPListen(ctx, workspace, sandbox, remotePort, localPort, bind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TCPListen", reflect.TypeOf((*MockGateway)(nil).TCPListen), ctx, workspace, sandbox, remotePort, localPort, bind)
}

// UpdateConfig mocks base method.
func (m *MockGateway) UpdateConfig(ctx context.Context, workspace string, u *types.ConfigUpdate) (*types.ConfigUpdateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateConfig", ctx, workspace, u)
	ret0, _ := ret[0].(*types.ConfigUpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateConfig indicates an expected call of UpdateConfig.
func (mr *MockGatewayMockRecorder) UpdateConfig(ctx, workspace, u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateConfig", reflect.TypeOf((*MockGateway)(nil).UpdateConfig), ctx, workspace, u)
}

// WatchSandbox mocks base method.
func (m *MockGateway) WatchSandbox(ctx context.Context, req *openshellv1.WatchSandboxRequest) (gateway.Stream[*openshellv1.SandboxStreamEvent], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WatchSandbox", ctx, req)
	ret0, _ := ret[0].(gateway.Stream[*openshellv1.SandboxStreamEvent])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchSandbox indicates an expected call of WatchSandbox.
func (mr *MockGatewayMockRecorder) WatchSandbox(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchSandbox", reflect.TypeOf((*MockGateway)(nil).WatchSandbox), ctx, req)
}
